#!/bin/bash

TARGET_IP=127.0.0.1
TARGET_PORT=14550


source ~/projects/precision-landing-companion/venv/bin/activate && \
mavproxy.py --source-system=41 --source-component=190 --target-system=1 --target-component=1 \
    --master=udp:${TARGET_IP}:${TARGET_PORT} --console
