#!/usr/bin/env python3
import inspect
from pathlib import Path
import datetime
import textwrap

# Typically use _file__ but it doesn't work when being run from platformio
src_file_path = inspect.getfile(lambda: None)
PROJECT_ROOT = Path(src_file_path).absolute().parent.parent
SOURCE_DIR = PROJECT_ROOT.joinpath('src')
BUILD_H_FILE = SOURCE_DIR.joinpath('build.h')

def main():
    w = 70
    print('*' * w)
    print()
    print('Generating build header file')
    build_datetime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    build_file = f'''\
    #ifndef BUILD_H
    #define BUILD_H

    // -- This file is automatically generated -- //

    #define BUILD_DATETIME "{build_datetime}"

    #endif
    '''

    with open(BUILD_H_FILE, 'w') as f:
        f.write(textwrap.dedent(build_file))

    print('Done')
    print()
    print('*' * w)

if '__file__' in globals():
    if __name__ == '__main__':
        main()
else:
    # Being called from platformio, we're not running as main script
    main()

