
from dataclasses import dataclass, asdict

# -- This file is autogenerated -- #

@dataclass
class TelemetryPacket:

    def to_json(self) -> str:
        return {
            'type': self.__class__.__name__.split('Telemetry')[-1],
            **asdict(self)
        }

@dataclass
class TelemetryStatus(TelemetryPacket):
    upTimeMs: int  # uint32_t
    cameraFps: int  # uint8_t
    freeHeap: int  # uint32_t

    _fmt = '<IBI'