
from dataclasses import dataclass, asdict
from telemetry_packet import TelemetryPacket

# -- This file is autogenerated -- #

@dataclass
class TelemetryStatus(TelemetryPacket):
    upTimeMs: int  # uint32_t
    cameraFps: int  # uint8_t
    freeHeap: int  # uint32_t
    quad_decimate: float  # float
    quad_sigma: float  # float
    refine_edges: bool  # bool
    decode_sharpening: float  # float

    _fmt = '<IBIffBf'